"""empty message

Revision ID: 919c7d119669
Revises: c6a4e8c9cf97
Create Date: 2020-08-31 16:41:22.905333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919c7d119669'
down_revision = 'c6a4e8c9cf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boy', sa.Column('age', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boy', 'age')
    # ### end Alembic commands ###
